[package]
name = "momo"
version = "0.1.0"
authors = ["sammoth <sammoth.th@gmail.com>"]
edition = "2018"

[dependencies]
rayon = "1.5.0"
flume = "0.9.2"
ignore = "0.4.16"
tree_magic = "0.2.3"
mime_guess = "2.0.3"
ffav = "4.3.8"
ape = "0.3.0"